version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/frontend/src
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/backend/src
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true

  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shupure
      MYSQL_USER: shiro
      MYSQL_PASSWORD: shiro06293
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3307"

volumes:
  db_data:
