CREATE DATABASE IF NOT EXISTS shupure;

USE shupure;

CREATE TABLE UserTable (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL
);

CREATE TABLE ChatRecipeTable (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    UserId INT NOT NULL,
    Title VARCHAR(100) NOT NULL,
    Food TEXT NOT NULL,
    Recipe TEXT NOT NULL,
    Drink VARCHAR(100) NOT NULL,
    LikeRecipe BOOLEAN NOT NULL,

    FOREIGN KEY (UserId) REFERENCES UserTable(Id)
);

