CREATE DATABASE IF NOT EXISTS shupure;

USE shupure;

CREATE TABLE UserTable (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL
);

CREATE TABLE PostTable (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(100) NOT NULL,
    PostTime DATETIME NOT NULL,
    UserId INT NOT NULL,
    duration INT NOT NULL,
    UseKnife BOOLEAN NOT NULL,
    UseFire BOOLEAN NOT NULL,
    image VARCHAR(100),
    FOREIGN KEY (UserId) REFERENCES UserTable(Id)
);

CREATE TABLE RecipeTable (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    PostId INT NOT NULL,
    Recipe TEXT NOT NULL,
    FOREIGN KEY (PostId) REFERENCES PostTable(Id)
);

CREATE TABLE FoodStuffTable (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    PostId INT NOT NULL,
    FoodName VARCHAR(50) NOT NULL,
    Amount VARCHAR(50) NOT NULL,
    FOREIGN KEY (PostId) REFERENCES PostTable(Id)
);

CREATE TABLE TagTable (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    TagName VARCHAR(50) NOT NULL
);

CREATE TABLE PostTagTable (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    PostId INT NOT NULL,
    TagID INT NOT NULL,
    FOREIGN KEY (PostId) REFERENCES PostTable(Id),
    FOREIGN KEY (TagID) REFERENCES TagTable(Id)
);

CREATE TABLE BookmarkTable (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    UserId INT NOT NULL,
    PostId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES UserTable(Id),
    FOREIGN KEY (PostId) REFERENCES PostTable(Id)
);

CREATE TABLE EnqueteTable (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    PostId INT NOT NULL,
    UserId INT NOT NULL,
    TagId INT NOT NULL,
    FOREIGN KEY (PostId) REFERENCES PostTable(Id),
    FOREIGN KEY (UserId) REFERENCES UserTable(Id),
    FOREIGN KEY (TagId) REFERENCES TagTable(Id)
);

